spring.application.name=inventory-service

server.servlet.context-path=/api/v1
server.port=9010

# Inventory Service DB
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=Bhuli@123
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jackson.serialization.indent_output=true
